window.quest = [
  {
    category: "英語",
    items: [
      { display: "hello", kana: "hello", romaji: ["hello"] },
      { display: "goodbye", kana: "goodbye", romaji: ["goodbye"] },
      { display: "morning", kana: "morning", romaji: ["morning"] },
      { display: "afternoon", kana: "afternoon", romaji: ["afternoon"] },
      { display: "evening", kana: "evening", romaji: ["evening"] },
      { display: "night", kana: "night", romaji: ["night"] },
      { display: "thankyou", kana: "thankyou", romaji: ["thankyou"] },
      { display: "please", kana: "please", romaji: ["please"] },
      { display: "sorry", kana: "sorry", romaji: ["sorry"] },
      { display: "welcome", kana: "welcome", romaji: ["welcome"] },
      { display: "student", kana: "student", romaji: ["student"] },
      { display: "teacher", kana: "teacher", romaji: ["teacher"] },
      { display: "school", kana: "school", romaji: ["school"] },
      { display: "class", kana: "class", romaji: ["class"] },
      { display: "lesson", kana: "lesson", romaji: ["lesson"] },
      { display: "study", kana: "study", romaji: ["study"] },
      { display: "practice", kana: "practice", romaji: ["practice"] },
      { display: "homework", kana: "homework", romaji: ["homework"] },
      { display: "schedule", kana: "schedule", romaji: ["schedule"] },
      { display: "result", kana: "result", romaji: ["result"] },
      { display: "start", kana: "start", romaji: ["start"] },
      { display: "end", kana: "end", romaji: ["end"] },
      { display: "open", kana: "open", romaji: ["open"] },
      { display: "close", kana: "close", romaji: ["close"] },
      { display: "check", kana: "check", romaji: ["check"] },
      { display: "confirm", kana: "confirm", romaji: ["confirm"] },
      { display: "finish", kana: "finish", romaji: ["finish"] },
      { display: "continue", kana: "continue", romaji: ["continue"] },
      { display: "prepare", kana: "prepare", romaji: ["prepare"] },
      { display: "submit", kana: "submit", romaji: ["submit"] },
      { display: "information", kana: "information", romaji: ["information"] },
      { display: "question", kana: "question", romaji: ["question"] },
      { display: "answer", kana: "answer", romaji: ["answer"] },
      { display: "problem", kana: "problem", romaji: ["problem"] },
      { display: "solution", kana: "solution", romaji: ["solution"] },
      { display: "example", kana: "example", romaji: ["example"] },
      { display: "method", kana: "method", romaji: ["method"] },
      { display: "system", kana: "system", romaji: ["system"] },
      { display: "status", kana: "status", romaji: ["status"] },
      { display: "process", kana: "process", romaji: ["process"] },
      { display: "computer", kana: "computer", romaji: ["computer"] },
      { display: "keyboard", kana: "keyboard", romaji: ["keyboard"] },
      { display: "mouse", kana: "mouse", romaji: ["mouse"] },
      { display: "monitor", kana: "monitor", romaji: ["monitor"] },
      { display: "printer", kana: "printer", romaji: ["printer"] },
      { display: "software", kana: "software", romaji: ["software"] },
      { display: "hardware", kana: "hardware", romaji: ["hardware"] },
      { display: "network", kana: "network", romaji: ["network"] },
      { display: "internet", kana: "internet", romaji: ["internet"] },
      { display: "browser", kana: "browser", romaji: ["browser"] },
      { display: "email", kana: "email", romaji: ["email"] },
      { display: "account", kana: "account", romaji: ["account"] },
      { display: "password", kana: "password", romaji: ["password"] },
      { display: "login", kana: "login", romaji: ["login"] },
      { display: "logout", kana: "logout", romaji: ["logout"] },
      { display: "security", kana: "security", romaji: ["security"] },
      { display: "backup", kana: "backup", romaji: ["backup"] },
      { display: "update", kana: "update", romaji: ["update"] },
      { display: "download", kana: "download", romaji: ["download"] },
      { display: "upload", kana: "upload", romaji: ["upload"] },
      { display: "file", kana: "file", romaji: ["file"] },
      { display: "folder", kana: "folder", romaji: ["folder"] },
      { display: "save", kana: "save", romaji: ["save"] },
      { display: "delete", kana: "delete", romaji: ["delete"] },
      { display: "copy", kana: "copy", romaji: ["copy"] },
      { display: "paste", kana: "paste", romaji: ["paste"] },
      { display: "setting", kana: "setting", romaji: ["setting"] },
      { display: "option", kana: "option", romaji: ["option"] },
      { display: "error", kana: "error", romaji: ["error"] },
      { display: "message", kana: "message", romaji: ["message"] },
      { display: "server", kana: "server", romaji: ["server"] },
      { display: "client", kana: "client", romaji: ["client"] },
      { display: "cloud", kana: "cloud", romaji: ["cloud"] },
      { display: "database", kana: "database", romaji: ["database"] },
      { display: "access", kana: "access", romaji: ["access"] },
      { display: "permission", kana: "permission", romaji: ["permission"] },
      { display: "connection", kana: "connection", romaji: ["connection"] },
      { display: "disconnect", kana: "disconnect", romaji: ["disconnect"] },
      { display: "performance", kana: "performance", romaji: ["performance"] },
      { display: "response", kana: "response", romaji: ["response"] },
      { display: "program", kana: "program", romaji: ["program"] },
      { display: "code", kana: "code", romaji: ["code"] },
      { display: "source", kana: "source", romaji: ["source"] },
      { display: "compile", kana: "compile", romaji: ["compile"] },
      { display: "execute", kana: "execute", romaji: ["execute"] },
      { display: "debug", kana: "debug", romaji: ["debug"] },
      { display: "function", kana: "function", romaji: ["function"] },
      { display: "variable", kana: "variable", romaji: ["variable"] },
      { display: "constant", kana: "constant", romaji: ["constant"] },
      { display: "array", kana: "array", romaji: ["array"] },
      { display: "object", kana: "object", romaji: ["object"] },
      { display: "class", kana: "class", romaji: ["class"] },
      { display: "method", kana: "method", romaji: ["method"] },
      { display: "argument", kana: "argument", romaji: ["argument"] },
      { display: "return", kana: "return", romaji: ["return"] },
      { display: "condition", kana: "condition", romaji: ["condition"] },
      { display: "loop", kana: "loop", romaji: ["loop"] },
      { display: "logic", kana: "logic", romaji: ["logic"] },
      { display: "syntax", kana: "syntax", romaji: ["syntax"] },
      { display: "exception", kana: "exception", romaji: ["exception"] },
      { display: "framework", kana: "framework", romaji: ["framework"] },
      { display: "library", kana: "library", romaji: ["library"] },
      { display: "module", kana: "module", romaji: ["module"] },
      { display: "package", kana: "package", romaji: ["package"] },
      { display: "version", kana: "version", romaji: ["version"] },
      { display: "release", kana: "release", romaji: ["release"] },
      { display: "repository", kana: "repository", romaji: ["repository"] },
      { display: "commit", kana: "commit", romaji: ["commit"] },
      { display: "branch", kana: "branch", romaji: ["branch"] },
      { display: "merge", kana: "merge", romaji: ["merge"] },
      { display: "office", kana: "office", romaji: ["office"] },
      { display: "company", kana: "company", romaji: ["company"] },
      { display: "business", kana: "business", romaji: ["business"] },
      { display: "document", kana: "document", romaji: ["document"] },
      { display: "report", kana: "report", romaji: ["report"] },
      { display: "meeting", kana: "meeting", romaji: ["meeting"] },
      { display: "contact", kana: "contact", romaji: ["contact"] },
      { display: "support", kana: "support", romaji: ["support"] },
      { display: "service", kana: "service", romaji: ["service"] },
      { display: "request", kana: "request", romaji: ["request"] },
      { display: "approve", kana: "approve", romaji: ["approve"] },
      { display: "reject", kana: "reject", romaji: ["reject"] },
      { display: "progress", kana: "progress", romaji: ["progress"] },
      { display: "deadline", kana: "deadline", romaji: ["deadline"] },
      { display: "priority", kana: "priority", romaji: ["priority"] },
      { display: "complete", kana: "complete", romaji: ["complete"] },
      { display: "success", kana: "success", romaji: ["success"] }
    ]
  },
  {
    category: "日本語",
    items: [
      // ===== あいさつ・基本 =====
      { display: "おはよう", kana: "おはよう", romaji: ["ohayou", "ohayo"] },
      { display: "こんにちは", kana: "こんにちは", romaji: ["konnichiwa", "konnitiwa"] },
      { display: "こんばんは", kana: "こんばんは", romaji: ["konbanwa", "konbanha"] },
      { display: "ありがとう", kana: "ありがとう", romaji: ["arigatou", "arigato"] },
      { display: "よろしく", kana: "よろしく", romaji: ["yoroshiku", "yorosiku"] },

      // ===== 学校・学生生活 =====
      { display: "学校", kana: "がっこう", romaji: ["gakkou", "gakko"] },
      { display: "専門学校", kana: "せんもんがっこう", romaji: ["senmongakkou"] },
      { display: "授業", kana: "じゅぎょう", romaji: ["jugyou", "zyugyou"] },
      { display: "学生", kana: "がくせい", romaji: ["gakusei"] },
      { display: "先生", kana: "せんせい", romaji: ["sensei"] },
      { display: "時間割", kana: "じかんわり", romaji: ["jikanwari"] },
      { display: "出席", kana: "しゅっせき", romaji: ["shusseki", "syusseki"] },
      { display: "欠席", kana: "けっせき", romaji: ["kesseki"] },
      { display: "成績", kana: "せいせき", romaji: ["seiseki"] },
      { display: "単位", kana: "たんい", romaji: ["tani, "tanni""] },

      // ===== 事務・手続 =====
      { display: "入学", kana: "にゅうがく", romaji: ["nyuugaku"] },
      { display: "出願", kana: "しゅつがん", romaji: ["shutsugan"] },
      { display: "合格", kana: "ごうかく", romaji: ["goukaku"] },
      { display: "受付", kana: "うけつけ", romaji: ["uketsuke"] },
      { display: "提出", kana: "ていしゅつ", romaji: ["teishutsu"] },
      { display: "確認", kana: "かくにん", romaji: ["kakunin"] },
      { display: "完了", kana: "かんりょう", romaji: ["kanryou"] },

      // ===== IT基礎 =====
      { display: "パソコン", kana: "ぱそこん", romaji: ["pasokon"] },
      { display: "キーボード", kana: "きーぼーど", romaji: ["kiiboodo", "ki-bo-do"] },
      { display: "マウス", kana: "まうす", romaji: ["mausu"] },
      { display: "ディスプレイ", kana: "でぃすぷれい", romaji: ["disupurei", "dhisupurei"] },
      { display: "インターネット", kana: "いんたーねっと", romaji: ["inta-netto", "intaanetto"] },
      { display: "ログイン", kana: "ろぐいん", romaji: ["roguin"] },
      { display: "ログアウト", kana: "ろぐあうと", romaji: ["roguauto"] },

      // ===== プログラミング =====
      { display: "プログラム", kana: "ぷろぐらむ", romaji: ["puroguramu"] },
      { display: "ソースコード", kana: "そーすこーど", romaji: ["soosukoodo"] },
      { display: "エラー", kana: "えらー", romaji: ["eraa"] },
      { display: "デバッグ", kana: "でばっぐ", romaji: ["debaggu"] },
      { display: "変数", kana: "へんすう", romaji: ["hensuu"] },
      { display: "関数", kana: "かんすう", romaji: ["kansuu"] },
      { display: "配列", kana: "はいれつ", romaji: ["hairetsu"] },
      { display: "条件", kana: "じょうけん", romaji: ["jouken", "zyouken"] },
      { display: "処理", kana: "しょり", romaji: ["shori", "syori"] },

      // ===== ネットワーク =====
      { display: "サーバー", kana: "さーばー", romaji: ["saabaa", "sa-ba-"] },
      { display: "ネットワーク", kana: "ねっとわーく", romaji: ["nettowaaku"] },
      { display: "通信", kana: "つうしん", romaji: ["tsuushin"] },
      { display: "接続", kana: "せつぞく", romaji: ["setsuzoku"] },
      { display: "設定", kana: "せってい", romaji: ["settei"] },

      // ===== クラウド・OS =====
      { display: "クラウド", kana: "くらうど", romaji: ["kuraudo"] },
      { display: "仮想環境", kana: "かそうかんきょう", romaji: ["kasoukankyou"] },
      { display: "Linux", kana: "りなっくす", romaji: ["rinakkusu"] },
      { display: "コマンド", kana: "こまんど", romaji: ["komando"] },
      { display: "ファイル", kana: "ふぁいる", romaji: ["fairu"] },
      { display: "保存", kana: "ほぞん", romaji: ["hozon"] },

      // ===== 就職・社会 =====
      { display: "就職", kana: "しゅうしょく", romaji: ["shuushoku"] },
      { display: "履歴書", kana: "りれきしょ", romaji: ["rirekisho"] },
      { display: "面接", kana: "めんせつ", romaji: ["mensetsu"] },
      { display: "内定", kana: "ないてい", romaji: ["naitei"] },
      { display: "社会人", kana: "しゃかいじん", romaji: ["shakaijin"] },

      // ===== 作業・業務 =====
      { display: "作業", kana: "さぎょう", romaji: ["sagyou"] },
      { display: "開始", kana: "かいし", romaji: ["kaishi"] },
      { display: "終了", kana: "しゅうりょう", romaji: ["shuuryou"] },
      { display: "修正", kana: "しゅうせい", romaji: ["shuusei"] },
      { display: "共有", kana: "きょうゆう", romaji: ["kyouyuu"] },
      { display: "連絡", kana: "れんらく", romaji: ["renraku"] },
      { display: "確認中", kana: "かくにんちゅう", romaji: ["kakuninchuu"] },
      { display: "対応中", kana: "たいおうちゅう", romaji: ["taiouchuu"] }
    ]
  }
];

// 互換（既存 program.js 用：当面維持）
window.mondailist = window.quest.map(cat => [
  cat.category,
  ...cat.items.map(q => q.kana)
]);
