window.quest = [
  {
    category: "英語",
    items: [
      { "display": "hello", "kana": "hello", "romaji": ["hello"], "canonical": "hello" },
      { "display": "goodbye", "kana": "goodbye", "romaji": ["goodbye"], "canonical": "goodbye" },
      { "display": "morning", "kana": "morning", "romaji": ["morning"], "canonical": "morning" },
      { "display": "afternoon", "kana": "afternoon", "romaji": ["afternoon"], "canonical": "afternoon" },
      { "display": "evening", "kana": "evening", "romaji": ["evening"], "canonical": "evening" },
      { "display": "night", "kana": "night", "romaji": ["night"], "canonical": "night" },
      { "display": "thankyou", "kana": "thankyou", "romaji": ["thankyou"], "canonical": "thankyou" },
      { "display": "please", "kana": "please", "romaji": ["please"], "canonical": "please" },
      { "display": "sorry", "kana": "sorry", "romaji": ["sorry"], "canonical": "sorry" },
      { "display": "welcome", "kana": "welcome", "romaji": ["welcome"], "canonical": "welcome" },
      { "display": "student", "kana": "student", "romaji": ["student"], "canonical": "student" },
      { "display": "teacher", "kana": "teacher", "romaji": ["teacher"], "canonical": "teacher" },
      { "display": "school", "kana": "school", "romaji": ["school"], "canonical": "school" },
      { "display": "class", "kana": "class", "romaji": ["class"], "canonical": "class" },
      { "display": "lesson", "kana": "lesson", "romaji": ["lesson"], "canonical": "lesson" },
      { "display": "study", "kana": "study", "romaji": ["study"], "canonical": "study" },
      { "display": "practice", "kana": "practice", "romaji": ["practice"], "canonical": "practice" },
      { "display": "homework", "kana": "homework", "romaji": ["homework"], "canonical": "homework" },
      { "display": "schedule", "kana": "schedule", "romaji": ["schedule"], "canonical": "schedule" },
      { "display": "result", "kana": "result", "romaji": ["result"], "canonical": "result" },
      { "display": "start", "kana": "start", "romaji": ["start"], "canonical": "start" },
      { "display": "end", "kana": "end", "romaji": ["end"], "canonical": "end" },
      { "display": "open", "kana": "open", "romaji": ["open"], "canonical": "open" },
      { "display": "close", "kana": "close", "romaji": ["close"], "canonical": "close" },
      { "display": "check", "kana": "check", "romaji": ["check"], "canonical": "check" },
      { "display": "confirm", "kana": "confirm", "romaji": ["confirm"], "canonical": "confirm" },
      { "display": "finish", "kana": "finish", "romaji": ["finish"], "canonical": "finish" },
      { "display": "continue", "kana": "continue", "romaji": ["continue"], "canonical": "continue" },
      { "display": "prepare", "kana": "prepare", "romaji": ["prepare"], "canonical": "prepare" },
      { "display": "submit", "kana": "submit", "romaji": ["submit"], "canonical": "submit" },
      { "display": "information", "kana": "information", "romaji": ["information"], "canonical": "information" },
      { "display": "question", "kana": "question", "romaji": ["question"], "canonical": "question" },
      { "display": "answer", "kana": "answer", "romaji": ["answer"], "canonical": "answer" },
      { "display": "problem", "kana": "problem", "romaji": ["problem"], "canonical": "problem" },
      { "display": "solution", "kana": "solution", "romaji": ["solution"], "canonical": "solution" },
      { "display": "example", "kana": "example", "romaji": ["example"], "canonical": "example" },
      { "display": "method", "kana": "method", "romaji": ["method"], "canonical": "method" },
      { "display": "system", "kana": "system", "romaji": ["system"], "canonical": "system" },
      { "display": "status", "kana": "status", "romaji": ["status"], "canonical": "status" },
      { "display": "process", "kana": "process", "romaji": ["process"], "canonical": "process" },
      { "display": "computer", "kana": "computer", "romaji": ["computer"], "canonical": "computer" },
      { "display": "keyboard", "kana": "keyboard", "romaji": ["keyboard"], "canonical": "keyboard" },
      { "display": "mouse", "kana": "mouse", "romaji": ["mouse"], "canonical": "mouse" },
      { "display": "monitor", "kana": "monitor", "romaji": ["monitor"], "canonical": "monitor" },
      { "display": "printer", "kana": "printer", "romaji": ["printer"], "canonical": "printer" },
      { "display": "software", "kana": "software", "romaji": ["software"], "canonical": "software" },
      { "display": "hardware", "kana": "hardware", "romaji": ["hardware"], "canonical": "hardware" },
      { "display": "network", "kana": "network", "romaji": ["network"], "canonical": "network" },
      { "display": "internet", "kana": "internet", "romaji": ["internet"], "canonical": "internet" },
      { "display": "browser", "kana": "browser", "romaji": ["browser"], "canonical": "browser" },
      { "display": "email", "kana": "email", "romaji": ["email"], "canonical": "email" },
      { "display": "account", "kana": "account", "romaji": ["account"], "canonical": "account" },
      { "display": "password", "kana": "password", "romaji": ["password"], "canonical": "password" },
      { "display": "login", "kana": "login", "romaji": ["login"], "canonical": "login" },
      { "display": "logout", "kana": "logout", "romaji": ["logout"], "canonical": "logout" },
      { "display": "security", "kana": "security", "romaji": ["security"], "canonical": "security" },
      { "display": "backup", "kana": "backup", "romaji": ["backup"], "canonical": "backup" },
      { "display": "update", "kana": "update", "romaji": ["update"], "canonical": "update" },
      { "display": "download", "kana": "download", "romaji": ["download"], "canonical": "download" },
      { "display": "upload", "kana": "upload", "romaji": ["upload"], "canonical": "upload" },
      { "display": "file", "kana": "file", "romaji": ["file"], "canonical": "file" },
      { "display": "folder", "kana": "folder", "romaji": ["folder"], "canonical": "folder" },
      { "display": "save", "kana": "save", "romaji": ["save"], "canonical": "save" },
      { "display": "delete", "kana": "delete", "romaji": ["delete"], "canonical": "delete" },
      { "display": "copy", "kana": "copy", "romaji": ["copy"], "canonical": "copy" },
      { "display": "paste", "kana": "paste", "romaji": ["paste"], "canonical": "paste" },
      { "display": "setting", "kana": "setting", "romaji": ["setting"], "canonical": "setting" },
      { "display": "option", "kana": "option", "romaji": ["option"], "canonical": "option" },
      { "display": "error", "kana": "error", "romaji": ["error"], "canonical": "error" },
      { "display": "message", "kana": "message", "romaji": ["message"], "canonical": "message" },
      { "display": "server", "kana": "server", "romaji": ["server"], "canonical": "server" },
      { "display": "client", "kana": "client", "romaji": ["client"], "canonical": "client" },
      { "display": "cloud", "kana": "cloud", "romaji": ["cloud"], "canonical": "cloud" },
      { "display": "database", "kana": "database", "romaji": ["database"], "canonical": "database" },
      { "display": "access", "kana": "access", "romaji": ["access"], "canonical": "access" },
      { "display": "permission", "kana": "permission", "romaji": ["permission"], "canonical": "permission" },
      { "display": "connection", "kana": "connection", "romaji": ["connection"], "canonical": "connection" },
      { "display": "disconnect", "kana": "disconnect", "romaji": ["disconnect"], "canonical": "disconnect" },
      { "display": "performance", "kana": "performance", "romaji": ["performance"], "canonical": "performance" },
      { "display": "response", "kana": "response", "romaji": ["response"], "canonical": "response" },
      { "display": "program", "kana": "program", "romaji": ["program"], "canonical": "program" },
      { "display": "code", "kana": "code", "romaji": ["code"], "canonical": "code" },
      { "display": "source", "kana": "source", "romaji": ["source"], "canonical": "source" },
      { "display": "compile", "kana": "compile", "romaji": ["compile"], "canonical": "compile" },
      { "display": "execute", "kana": "execute", "romaji": ["execute"], "canonical": "execute" },
      { "display": "debug", "kana": "debug", "romaji": ["debug"], "canonical": "debug" },
      { "display": "function", "kana": "function", "romaji": ["function"], "canonical": "function" },
      { "display": "variable", "kana": "variable", "romaji": ["variable"], "canonical": "variable" },
      { "display": "constant", "kana": "constant", "romaji": ["constant"], "canonical": "constant" },
      { "display": "array", "kana": "array", "romaji": ["array"], "canonical": "array" },
      { "display": "object", "kana": "object", "romaji": ["object"], "canonical": "object" },
      { "display": "argument", "kana": "argument", "romaji": ["argument"], "canonical": "argument" },
      { "display": "return", "kana": "return", "romaji": ["return"], "canonical": "return" },
      { "display": "condition", "kana": "condition", "romaji": ["condition"], "canonical": "condition" },
      { "display": "loop", "kana": "loop", "romaji": ["loop"], "canonical": "loop" },
      { "display": "logic", "kana": "logic", "romaji": ["logic"], "canonical": "logic" },
      { "display": "syntax", "kana": "syntax", "romaji": ["syntax"], "canonical": "syntax" },
      { "display": "exception", "kana": "exception", "romaji": ["exception"], "canonical": "exception" },
      { "display": "framework", "kana": "framework", "romaji": ["framework"], "canonical": "framework" },
      { "display": "library", "kana": "library", "romaji": ["library"], "canonical": "library" },
      { "display": "module", "kana": "module", "romaji": ["module"], "canonical": "module" },
      { "display": "package", "kana": "package", "romaji": ["package"], "canonical": "package" },
      { "display": "version", "kana": "version", "romaji": ["version"], "canonical": "version" },
      { "display": "release", "kana": "release", "romaji": ["release"], "canonical": "release" },
      { "display": "repository", "kana": "repository", "romaji": ["repository"], "canonical": "repository" },
      { "display": "commit", "kana": "commit", "romaji": ["commit"], "canonical": "commit" },
      { "display": "branch", "kana": "branch", "romaji": ["branch"], "canonical": "branch" },
      { "display": "merge", "kana": "merge", "romaji": ["merge"], "canonical": "merge" },
      { "display": "office", "kana": "office", "romaji": ["office"], "canonical": "office" },
      { "display": "company", "kana": "company", "romaji": ["company"], "canonical": "company" },
      { "display": "business", "kana": "business", "romaji": ["business"], "canonical": "business" },
      { "display": "document", "kana": "document", "romaji": ["document"], "canonical": "document" },
      { "display": "report", "kana": "report", "romaji": ["report"], "canonical": "report" },
      { "display": "meeting", "kana": "meeting", "romaji": ["meeting"], "canonical": "meeting" },
      { "display": "contact", "kana": "contact", "romaji": ["contact"], "canonical": "contact" },
      { "display": "support", "kana": "support", "romaji": ["support"], "canonical": "support" },
      { "display": "service", "kana": "service", "romaji": ["service"], "canonical": "service" },
      { "display": "request", "kana": "request", "romaji": ["request"], "canonical": "request" },
      { "display": "approve", "kana": "approve", "romaji": ["approve"], "canonical": "approve" },
      { "display": "reject", "kana": "reject", "romaji": ["reject"], "canonical": "reject" },
      { "display": "progress", "kana": "progress", "romaji": ["progress"], "canonical": "progress" },
      { "display": "deadline", "kana": "deadline", "romaji": ["deadline"], "canonical": "deadline" },
      { "display": "priority", "kana": "priority", "romaji": ["priority"], "canonical": "priority" },
      { "display": "complete", "kana": "complete", "romaji": ["complete"], "canonical": "complete" },
      { "display": "success", "kana": "success", "romaji": ["success"], "canonical": "success" }
    ]
  },
  {
    category: "日本語",
    items:[
  {"display":"はじめまして","kana":"はじめまして","romaji":["hajimemashite","hajimemasite","hazimemashite","hazimemasite"],"canonical":"hajimemashite"},
  {"display":"失礼します","kana":"しつれいします","romaji":["shitsureishimasu","shitsureisimasu","shitureishimasu","shitureisimasu","sitsureishimasu","sitsureisimasu","situreishimasu","situreisimasu"],"canonical":"shitsureishimasu"},
  {"display":"お疲れさまでした","kana":"おつかれさまでした","romaji":["otsukaresamadeshita","otsukaresamadesita","otukaresamadeshita","otukaresamadesita"],"canonical":"otsukaresamadeshita"},
  {"display":"了解しました","kana":"りょうかいしました","romaji":["ryoukaishimashita","ryoukaishimasita","ryoukaisimashita","ryoukaisimasita"],"canonical":"ryoukaishimashita"},
  {"display":"確認します","kana":"かくにんします","romaji":["kakuninnshimasu","kakuninnsimasu","kakuninshimasu","kakuninsimasu"],"canonical":"kakuninsimasu"},
  {"display":"入学","kana":"にゅうがく","romaji":["nyuugaku"],"canonical":"nyuugaku"},
  {"display":"出願","kana":"しゅつがん","romaji":["shutsugann","shutugann","syutsugann","syutugann"],"canonical":"shutsugann"},
  {"display":"合格通知","kana":"ごうかくつうち","romaji":["goukakutsuuchi","goukakutsuuti","goukakutuuchi","goukakutuuti"],"canonical":"goukakutsuuchi"},
  {"display":"学生証","kana":"がくせいしょう","romaji":["gakuseishou","gakuseisyou"],"canonical":"gakuseishou"},
  {"display":"授業開始","kana":"じゅぎょうかいし","romaji":["jugyoukaishi","jugyoukaisi","jyugyoukaishi","jyugyoukaisi","zyugyoukaishi","zyugyoukaisi"],"canonical":"jugyoukaishi"},
  {"display":"時間割","kana":"じかんわり","romaji":["jikannwari","jikanwari","zikannwari","zikanwari"],"canonical":"jikanwari"},
  {"display":"出席確認","kana":"しゅっせきかくにん","romaji":["shussekikakuninn","syussekikakuninn"],"canonical":"shussekikakuninn"},
  {"display":"事務局","kana":"じむきょく","romaji":["jimukyoku","zimukyoku"],"canonical":"jimukyoku"},
  {"display":"書類提出","kana":"しょるいていしゅつ","romaji":["shoruiteishutsu","shoruiteishutu","shoruiteisyutsu","shoruiteisyutu","syoruiteishutsu","syoruiteishutu","syoruiteisyutsu","syoruiteisyutu"],"canonical":"shoruiteishutsu"},
  {"display":"受付完了","kana":"うけつけかんりょう","romaji":["uketsukekannryou","uketsukekanryou","uketukekannryou","uketukekanryou"],"canonical":"uketsukekanryou"},
  {"display":"パソコン","kana":"ぱそこん","romaji":["pasokonn"],"canonical":"pasokonn"},
  {"display":"キーボード","kana":"きーぼーど","romaji":["ki-bo-do"],"canonical":"ki-bo-do"},
  {"display":"マウス","kana":"まうす","romaji":["mausu"],"canonical":"mausu"},
  {"display":"ディスプレイ","kana":"でぃすぷれい","romaji":["delisupurei","dexisupurei","dhisupurei"],"canonical":"dhisupurei"},
  {"display":"インターネット","kana":"いんたーねっと","romaji":["innta-netto","inta-netto"],"canonical":"innta-netto"},
  {"display":"ウェブサイト","kana":"うぇぶさいと","romaji":["ulebusaito","uxebusaito","webusaito"],"canonical":"webusaito"},
  {"display":"ログイン","kana":"ろぐいん","romaji":["roguinn"],"canonical":"roguinn"},
  {"display":"ログアウト","kana":"ろぐあうと","romaji":["roguauto"],"canonical":"roguauto"},
  {"display":"アカウント","kana":"あかうんと","romaji":["akaunnto","akaunto"],"canonical":"akaunnto"},
  {"display":"パスワード","kana":"ぱすわーど","romaji":["pasuwa-do"],"canonical":"pasuwa-do"},
  {"display":"ファイル保存","kana":"ふぁいるほぞん","romaji":["fairuhozonn","fulairuhozonn","fuxairuhozonn","hulairuhozonn","huxairuhozonn"],"canonical":"fairuhozonn"},
  {"display":"プログラム","kana":"ぷろぐらむ","romaji":["puroguramu"],"canonical":"puroguramu"},
  {"display":"ソースコード","kana":"そーすこーど","romaji":["so-suko-do"],"canonical":"so-suko-do"},
  {"display":"エラー","kana":"えらー","romaji":["era-"],"canonical":"era-"},
  {"display":"デバッグ","kana":"でばっぐ","romaji":["debaggu"],"canonical":"debaggu"},
  {"display":"コンパイル","kana":"こんぱいる","romaji":["konnpairu","konpairu"],"canonical":"konnpairu"},
  {"display":"変数","kana":"へんすう","romaji":["hennsuu","hensuu"],"canonical":"hensuu"},
  {"display":"条件分岐","kana":"じょうけんぶんき","romaji":["joukenbunki","joukenbunnki","joukennbunki","joukennbunnki","jyoukenbunki","jyoukenbunnki","jyoukennbunki","jyoukennbunnki","zyoukenbunki","zyoukenbunnki","zyoukennbunki","zyoukennbunnki"],"canonical":"joukenbunki"},
  {"display":"繰り返し処理","kana":"くりかえししょり","romaji":["kurikaeshishori","kurikaeshisyori","kurikaesishori","kurikaesisyori"],"canonical":"kurikaeshishori"},
  {"display":"関数呼び出し","kana":"かんすうよびだし","romaji":["kannsuuyobidashi","kannsuuyobidasi","kansuuyobidashi","kansuuyobidasi"],"canonical":"kansuuyobidashi"},
  {"display":"実行結果","kana":"じっこうけっか","romaji":["jikkoukekka","zikkoukekka"],"canonical":"jikkoukekka"},
  {"display":"出発","kana":"しゅっぱつ","romaji":["shuppatsu","shuppatu","syuppatsu","syuppatu"],"canonical":"shuppatsu"},
  {"display":"到着","kana":"とうちゃく","romaji":["touchaku","toutyaku"],"canonical":"touchaku"},
  {"display":"準備完了","kana":"じゅんびかんりょう","romaji":["junbikannryou","junbikanryou","junnbikannryou","junnbikanryou","jyunbikannryou","jyunbikanryou","jyunnbikannryou","jyunnbikanryou","zyunbikannryou","zyunbikanryou","zyunnbikannryou","zyunnbikanryou"],"canonical":"junbikanryou"},
  {"display":"確認中","kana":"かくにんちゅう","romaji":["kakuninchuu","kakuninnchuu","kakuninntyuu","kakunintyuu"],"canonical":"kakuninchuu"},
  {"display":"対応中","kana":"たいおうちゅう","romaji":["taiouchuu","taioutyuu"],"canonical":"taiouchuu"},
  {"display":"再確認","kana":"さいかくにん","romaji":["saikakuninn"],"canonical":"saikakuninn"},
  {"display":"問題なし","kana":"もんだいなし","romaji":["mondainashi","mondainasi","monndainashi","monndainasi"],"canonical":"mondainashi"},
  {"display":"修正完了","kana":"しゅうせいかんりょう","romaji":["shuuseikannryou","shuuseikanryou","syuuseikannryou","syuuseikanryou"],"canonical":"shuuseikanryou"},
  {"display":"連絡事項","kana":"れんらくじこう","romaji":["rennrakujikou","rennrakuzikou","renrakujikou","renrakuzikou"],"canonical":"renrakujikou"},
  {"display":"共有します","kana":"きょうゆうします","romaji":["kyouyuushimasu","kyouyuusimasu"],"canonical":"kyouyuushimasu"},
  {"display":"作業開始","kana":"さぎょうかいし","romaji":["sagyoukaishi","sagyoukaisi"],"canonical":"sagyoukaishi"},
  {"display":"作業終了","kana":"さぎょうしゅうりょう","romaji":["sagyoushuuryou","sagyousyuuryou"],"canonical":"sagyoushuuryou"},
  {"display":"本日分","kana":"ほんじつぶん","romaji":["honjitsubunn","honjitubunn","honnjitsubunn","honnjitubunn","honnzitsubunn","honnzitubunn","honzitsubunn","honzitubunn"],"canonical":"honjitsubunn"},
  {"display":"明日以降","kana":"あしたいこう","romaji":["ashitaikou","asitaikou"],"canonical":"ashitaikou"},
  {"display":"期限厳守","kana":"きげんげんしゅ","romaji":["kigengennshu","kigengennsyu","kigengenshu","kigengensyu","kigenngennshu","kigenngennsyu","kigenngenshu","kigenngensyu"],"canonical":"kigengenshu"},
  {"display":"提出済み","kana":"ていしゅつずみ","romaji":["teishutsuzumi","teishutuzumi","teisyutsuzumi","teisyutuzumi"],"canonical":"teishutsuzumi"},
  {"display":"未提出","kana":"みていしゅつ","romaji":["miteishutsu","miteishutu","miteisyutsu","miteisyutu"],"canonical":"miteishutsu"},
  {"display":"確認待ち","kana":"かくにんまち","romaji":["kakunimmachi","kakuninmachi","kakuninmati","kakuninnmachi","kakuninnmati"],"canonical":"kakunimmachi"},
  {"display":"承認済み","kana":"しょうにんずみ","romaji":["shouninnzumi","shouninzumi","syouninnzumi","syouninzumi"],"canonical":"shouninzumi"},
  {"display":"差し戻し","kana":"さしもどし","romaji":["sashimodoshi","sashimodosi","sasimodoshi","sasimodosi"],"canonical":"sashimodoshi"},
  {"display":"願書受付","kana":"がんしょうけつけ","romaji":["gannshouketsuke","gannshouketuke","gannsyouketsuke","gannsyouketuke","ganshouketsuke","ganshouketuke","gansyouketsuke","gansyouketuke"],"canonical":"ganshouketsuke"},
  {"display":"入学手続","kana":"にゅうがくてつづき","romaji":["nyuugakutetsuduki","nyuugakutetsuzuki","nyuugakutetuduki","nyuugakutetuzuki"],"canonical":"nyuugakutetsuzuki"},
  {"display":"学籍番号","kana":"がくせきばんごう","romaji":["gakusekibangou","gakusekibanngou"],"canonical":"gakusekibangou"},
  {"display":"履修登録","kana":"りしゅうとうろく","romaji":["rishuutouroku","risyuutouroku"],"canonical":"rishuutouroku"},
  {"display":"成績評価","kana":"せいせきひょうか","romaji":["seisekihyouka"],"canonical":"seisekihyouka"},
  {"display":"単位取得","kana":"たんいしゅとく","romaji":["tanishutoku","tannishutoku","tannisyutoku"],"canonical":"tanishutoku"},
  {"display":"出席率","kana":"しゅっせきりつ","romaji":["shussekiritsu","shussekiritu","syussekiritsu","syussekiritu"],"canonical":"shussekiritsu"},
  {"display":"欠席連絡","kana":"けっせきれんらく","romaji":["kessekirennraku","kessekirenraku"],"canonical":"kessekirenraku"},
  {"display":"補講案内","kana":"ほこうあんない","romaji":["hokouannai","hokouannnai"],"canonical":"hokouannai"},
  {"display":"休講情報","kana":"きゅうこうじょうほう","romaji":["kyuukoujouhou","kyuukoujyouhou","kyuukouzyouhou"],"canonical":"kyuukoujouhou"},
  {"display":"就職支援","kana":"しゅうしょくしえん","romaji":["shuushokushienn","shuushokusienn","shuusyokushienn","shuusyokusienn","syuushokushienn","syuushokusienn","syuusyokushienn","syuusyokusienn"],"canonical":"shuushokushienn"},
  {"display":"企業説明会","kana":"きぎょうせつめいかい","romaji":["kigyousetsumeikai","kigyousetumeikai"],"canonical":"kigyousetsumeikai"},
  {"display":"進路相談","kana":"しんろそうだん","romaji":["shinnrosoudann","shinrosoudann","sinnrosoudann","sinrosoudann"],"canonical":"shinrosoudann"},
  {"display":"内定通知","kana":"ないていつうち","romaji":["naiteitsuuchi","naiteitsuuti","naiteituuchi","naiteituuti"],"canonical":"naiteitsuuchi"},
  {"display":"卒業要件","kana":"そつぎょうようけん","romaji":["sotsugyouyoukenn","sotugyouyoukenn"],"canonical":"sotsugyouyoukenn"},
  {"display":"卒業証書","kana":"そつぎょうしょうしょ","romaji":["sotsugyoushousho","sotsugyoushousyo","sotsugyousyousho","sotsugyousyousyo","sotugyoushousho","sotugyoushousyo","sotugyousyousho","sotugyousyousyo"],"canonical":"sotsugyoushousho"},
  {"display":"証明書発行","kana":"しょうめいしょはっこう","romaji":["shoumeishohakkou","shoumeisyohakkou","syoumeishohakkou","syoumeisyohakkou"],"canonical":"shoumeishohakkou"},
  {"display":"事務手続","kana":"じむてつづき","romaji":["jimutetsuduki","jimutetsuzuki","jimutetuduki","jimutetuzuki","zimutetsuduki","zimutetsuzuki","zimutetuduki","zimutetuzuki"],"canonical":"jimutetsuzuki"},
  {"display":"窓口対応","kana":"まどぐちたいおう","romaji":["madoguchitaiou","madogutitaiou"],"canonical":"madoguchitaiou"},
  {"display":"問い合わせ対応","kana":"といあわせたいおう","romaji":["toiawasetaiou"],"canonical":"toiawasetaiou"},
  {"display":"電源投入","kana":"でんげんとうにゅう","romaji":["dengenntounyuu","dengentounyuu","denngenntounyuu","denngentounyuu"],"canonical":"dengentounyuu"},
  {"display":"再起動","kana":"さいきどう","romaji":["saikidou"],"canonical":"saikidou"},
  {"display":"シャットダウン","kana":"しゃっとだうん","romaji":["shattodaunn","syattodaunn"],"canonical":"shattodaunn"},
  {"display":"ユーザー名","kana":"ゆーざーめい","romaji":["yu-za-mei"],"canonical":"yu-za-mei"},
  {"display":"管理者権限","kana":"かんりしゃけんげん","romaji":["kannrishakengenn","kannrishakenngenn","kannrisyakengenn","kannrisyakenngenn","kanrishakengenn","kanrishakenngenn","kanrisyakengenn","kanrisyakenngenn"],"canonical":"kanrishakengenn"},
  {"display":"アクセス権","kana":"あくせすけん","romaji":["akusesukenn"],"canonical":"akusesukenn"},
  {"display":"共有フォルダ","kana":"きょうゆうふぉるだ","romaji":["kyouyuuforuda","kyouyuufuloruda","kyouyuufuxoruda","kyouyuuhuloruda","kyouyuuhuxoruda"],"canonical":"kyouyuuforuda"},
  {"display":"バックアップ","kana":"ばっくあっぷ","romaji":["bakkuappu"],"canonical":"bakkuappu"},
  {"display":"復元作業","kana":"ふくげんさぎょう","romaji":["fukugennsagyou","fukugensagyou","hukugennsagyou","hukugensagyou"],"canonical":"fukugensagyou"},
  {"display":"更新確認","kana":"こうしんかくにん","romaji":["koushinkakuninn","koushinnkakuninn","kousinkakuninn","kousinnkakuninn"],"canonical":"koushinkakuninn"},
  {"display":"通信エラー","kana":"つうしんえらー","romaji":["tsuushinera-","tsuushinnera-","tsuusinnera-","tuushinnera-","tuusinnera-"],"canonical":"tsuushinera-"},
  {"display":"接続確認","kana":"せつぞくかくにん","romaji":["setsuzokukakuninn","setuzokukakuninn"],"canonical":"setsuzokukakuninn"},
  {"display":"有線接続","kana":"ゆうせんせつぞく","romaji":["yuusennsetsuzoku","yuusennsetuzoku","yuusensetsuzoku","yuusensetuzoku"],"canonical":"yuusensetsuzoku"},
  {"display":"無線接続","kana":"むせんせつぞく","romaji":["musennsetsuzoku","musennsetuzoku","musensetsuzoku","musensetuzoku"],"canonical":"musensetsuzoku"},
  {"display":"ブラウザ起動","kana":"ぶらうざきどう","romaji":["burauzakidou"],"canonical":"burauzakidou"},
  {"display":"検索結果","kana":"けんさくけっか","romaji":["kennsakukekka","kensakukekka"],"canonical":"kensakukekka"},
  {"display":"履歴削除","kana":"りれきさくじょ","romaji":["rirekisakujo","rirekisakujyo","rirekisakuzyo"],"canonical":"rirekisakujo"},
  {"display":"キャッシュ削除","kana":"きゃっしゅさくじょ","romaji":["kyasshusakujo","kyasshusakujyo","kyasshusakuzyo","kyassyusakujo","kyassyusakujyo","kyassyusakuzyo"],"canonical":"kyasshusakujo"},
  {"display":"セキュリティ更新","kana":"せきゅりてぃこうしん","romaji":["sekyuritelikoushinn","sekyuritelikousinn","sekyuritexikoushinn","sekyuritexikousinn","sekyurithikoushin"],"canonical":"sekyurithikoushin"},
  {"display":"開発環境","kana":"かいはつかんきょう","romaji":["kaihatsukankyou","kaihatsukannkyou","kaihatukankyou","kaihatukannkyou"],"canonical":"kaihatsukankyou"},
  {"display":"実行確認","kana":"じっこうかくにん","romaji":["jikkoukakunin","jikkoukakuninn","zikkoukakuninn"],"canonical":"jikkoukakunin"},
  {"display":"構文エラー","kana":"こうぶんえらー","romaji":["koubunera-","koubunnera-"],"canonical":"koubunera-"},
  {"display":"論理エラー","kana":"ろんりえらー","romaji":["ronnriera-","ronriera-"],"canonical":"ronriera-"},
  {"display":"コメントアウト","kana":"こめんとあうと","romaji":["komenntoauto","komentoauto"],"canonical":"komentoauto"},
  {"display":"変数宣言","kana":"へんすうせんげん","romaji":["hennsuusengenn","hennsuusenngenn","hensuusengen","hensuusengenn","hensuusenngenn"],"canonical":"hensuusengen"},
  {"display":"型指定","kana":"かたしてい","romaji":["katashitei","katasitei"],"canonical":"katashitei"},
  {"display":"配列操作","kana":"はいれつそうさ","romaji":["hairetsusousa","hairetusousa"],"canonical":"hairetsusousa"},
  {"display":"条件判定","kana":"じょうけんはんてい","romaji":["joukenhanntei","joukenhantei","joukennhanntei","joukennhantei","jyoukenhanntei","jyoukenhantei","jyoukennhanntei","jyoukennhantei","zyoukenhanntei","zyoukenhantei","zyoukennhanntei","zyoukennhantei"],"canonical":"joukenhantei"}
]


  }
];

// 互換（既存 program.js 用：当面維持）
window.mondailist = window.quest.map(cat => [
  cat.category,
  ...cat.items.map(q => q.kana)
]);
